site_name: OptimumDynamics Help File

nav:
    - Home: index.md
    - Welcome: welcome.md
    - Getting Started:
      - Software Requirements: 1_Getting_Started/A_Software_Requirements.md
      - Installation: 1_Getting_Started/B_Installation.md
      - Licensing: 1_Getting_Started/C_Licensing.md
      - Starting a Project: 1_Getting_Started/D_Starting_a_Project.md
    - Detailed Guide:
      - Introduction: 2_Detailed_Guide/A_Introduction.md
      - Understanding Vehicle Design: 2_Detailed_Guide/B_Understanding_Vehicle_Design.md
      - Simulation: 2_Detailed_Guide/C_Simulation.md
      - Analysis: 2_Detailed_Guide/D_Analysis.md
      - Output Variable Definitions: 2_Detailed_Guide/E_Output_Variable_Definitions.md
    - Additional Information: 
      - Hot Keys and File Types: 3_Additional_Information/A_Hot_Keys_and_File_Types.md
      - Importing and Exporting Data: 3_Additional_Information/B_Importing_and_Exporting_Data.md
      - Starting Parameters: 3_Additional_Information/C_Starting_Parameters.md
      - 3D Visualization: 3_Additional_Information/D_3D_Visualization.md
      - FAQ: 3_Additional_Information/E_FAQ.md


theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette: 
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/optimum_tire_icon.svg'
  favicon: 'img/OptimumDynamics.ico'
  language: 'en'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

repo_name: 'Need further assistance?'
repo_url: 'http://www.optimumg.com/contact/software-support/'

extra:
  social:
    - type: 'globe'
      link: 'http://www.optimumg.com/'
    - type: 'facebook'
      link: 'https://www.facebook.com/OptimumG/'
    - type: 'twitter'
      link: 'https://twitter.com/g_optimum'
    - type: 'instagram'
      link: 'https://www.instagram.com/optimumg/?hl=en'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/optimumg'

copyright: 'Copyright © OptimumG 2019'

use_directory_urls: false